name: CI/CD deploy to lightsail
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 21.x

      - name: Install Dependencies
        run: cd ./apps/frontend && npm install

      - name: Copy .env file
        run: cp ./.env.prod ./apps/frontend/.env

      - name: Check Typescript
        run: cd ./apps/frontend && npm run tsc

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          port: ${{ secrets.DEPLOY_PORT }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            REPO_DIR=~/repository
            cd ${REPO_DIR}
            git pull origin main
            cp .env.prod apps/backend/.env
            cp .env.prod apps/frontend/.env
            cd apps/frontend
            npm install
            npm run build
            rm -rf ~/stack/html
            cp -rf ${REPO_DIR}/apps/frontend/dist ~/stack/html
            sudo systemctl restart gunicorn.service
